# Generated by Django 4.1.3 on 2022-11-20 04:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('statement', models.CharField(max_length=300)),
                ('audio', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('date_modification', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quizId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.quiz')),
            ],
        ),
    ]
