# Generated by Django 4.1.3 on 2022-11-20 14:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import words.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        ('phrase', '0001_initial'),
        ('questionWords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('statement', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=words.models.upload_to)),
                ('isQuestionWord', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('date_modification', models.DateTimeField(blank=True, null=True)),
                ('phraseId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phrase.phrase')),
                ('questionId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('questionWordId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionWords.questionword')),
            ],
        ),
    ]
